Repository JamboreeStation/Jamboree-Station, pull requests merged in 2025-09, with the labels that each got.

#75 Giant snake tails from harmony
  Resources/Locale/en-US/_CD/markings/reptilian.ftl
  Resources/Prototypes/_CD/Entities/Mobs/Customization/Markings/reptilian.yml
  Resources/Textures/_CD/Mobs/Customization/snaketail.rsi/meta.json
  Resources/Textures/_CD/Mobs/Customization/snaketail.rsi/tail_snake_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketail.rsi/tail_snake_secondary.png
  Resources/Textures/_CD/Mobs/Customization/snaketail.rsi/tail_snake_wag_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketail.rsi/tail_snake_wag_secondary.png
  Resources/Textures/_CD/Mobs/Customization/snaketaildual.rsi/meta.json
  Resources/Textures/_CD/Mobs/Customization/snaketaildual.rsi/tail_snake_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketaildual.rsi/tail_snake_secondary.png
  Resources/Textures/_CD/Mobs/Customization/snaketaildual.rsi/tail_snake_wag_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketaildual.rsi/tail_snake_wag_secondary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailstripe.rsi/meta.json
  Resources/Textures/_CD/Mobs/Customization/snaketailstripe.rsi/tail_snake_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailstripe.rsi/tail_snake_secondary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailstripe.rsi/tail_snake_wag_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailstripe.rsi/tail_snake_wag_secondary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailunder.rsi/meta.json
  Resources/Textures/_CD/Mobs/Customization/snaketailunder.rsi/tail_snake_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailunder.rsi/tail_snake_secondary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailunder.rsi/tail_snake_wag_primary.png
  Resources/Textures/_CD/Mobs/Customization/snaketailunder.rsi/tail_snake_wag_secondary.png
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: No C#

#79 Re add speed boots
  Resources/Prototypes/Recipes/Lathes/Packs/science.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/Research/civilianservices.yml
Labels: S: Untriaged, Changes: No C#, size/S

#80 Replace NY/DV bluespace with Goob bluespace
  Resources/Prototypes/_EinsteinEngines/Entities/Structures/Specific/oracle.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Materials/materials.yml
Labels: S: Untriaged, Changes: No C#, size/S

#82 Ghost respawn
  Content.Client/Content.Client.csproj
  Content.Client/Ghost/GhostSystem.cs
  Content.Client/UserInterface/Systems/Ghost/Controls/GhostRespawnRulesWindow.xaml
  Content.Client/UserInterface/Systems/Ghost/Controls/GhostRespawnRulesWindow.xaml.cs
  Content.Client/UserInterface/Systems/Ghost/GhostUIController.cs
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
  Content.Client/_NF/Respawn/RespawnSystem.cs
  Content.Server/Content.Server.csproj
  Content.Server/GameTicking/GameTicker.Spawning.cs
  Content.Server/ServerUpdates/ServerUpdateManager.cs
  Content.Server/_NF/Commands/GhostRespawnCommand.cs
  Content.Server/_NF/Respawn/RespawnResetComponent.cs
  Content.Server/_NF/Respawn/RespawnSystem.cs
  Content.Shared/Content.Shared.csproj
  Content.Shared/_NF/CCVars/CCVars.cs
  Content.Shared/_NF/Respawn/RespawnResetEvent.cs
  Resources/Locale/en-US/_NF/respawn/respawn-system.ftl
Labels: S: Untriaged, size/M, Changes: UI

#88 ClownOps has min requirement like other nukeop gamerules.
  Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Labels: size/XS, S: Untriaged, Changes: No C#

#85 Pleebnar: Little Green Pests
  Content.Client/_Imp/Pleebnar/PleebnarTelepathyBoundUserInterface.cs
  Content.Client/_Imp/Pleebnar/PleebnarTelepathyWindow.xaml
  Content.Client/_Imp/Pleebnar/PleebnarTelepathyWindow.xaml.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/_Imp/Pleebnar/PleebnarGibSystem.cs
  Content.Server/_Imp/Pleebnar/PleebnarTelepathySystem.cs
  Content.Shared/_Imp/Drone/Pleebnar/Components/PleebnarGibActionComponent.cs
  Content.Shared/_Imp/Drone/Pleebnar/Components/PleebnarGibbableComponent.cs
  Content.Shared/_Imp/Drone/Pleebnar/Components/PleebnarTelepathyActionComponent.cs
  Content.Shared/_Imp/Drone/Pleebnar/PleebnarVisionPrototype.cs
  Content.Shared/_Imp/Drone/Pleebnar/SharedPleebnarGibSystem.cs
  Content.Shared/_Imp/Drone/Pleebnar/SharedPleebnarTelepathySystem.cs
  Resources/Audio/_Impstation/Animals/attributions.yml
  Resources/Audio/_Impstation/Animals/pleebnar_scream.ogg
  Resources/Audio/_Impstation/Animals/pleebnar_speak.ogg
  Resources/Audio/_Impstation/Animals/pleebnar_squeak.ogg
  Resources/Audio/_Impstation/Animals/pleebnar_weird.ogg
  Resources/Locale/en-US/_Imp/accent/animals.ftl
  Resources/Locale/en-US/_Imp/pleebnar/pleebnar-vision.ftl
  Resources/Locale/en-US/_Imp/pleebnar/pleebnar.ftl
  Resources/Locale/en-US/_Imp/reagents/meta/biological.ftl
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
  Resources/Prototypes/GameRules/pests.yml
  Resources/Prototypes/_Imp/Accents/full_replacements.yml
  Resources/Prototypes/_Imp/Actions/pleebnar.yml
  Resources/Prototypes/_Imp/Body/Organs/pleebnar.yml
  Resources/Prototypes/_Imp/Body/Prototypes/Animal/pleebnar.yml
  Resources/Prototypes/_Imp/Damage/modifier_sets.yml
  Resources/Prototypes/_Imp/Pleebnars/Pleebnar_Visions.yml
  Resources/Prototypes/_Imp/Pleebnars/Pleebnars.yml
  Resources/Prototypes/_Imp/Reagents/biological.yml
  Resources/Prototypes/_Impstation/Voice/speech_emote_sounds.yml
  Resources/Prototypes/_Impstation/Voice/speech_sounds.yml
  Resources/Textures/_Goobstation/Changeling/changeling_abilities.rsi/meta.json
  Resources/Textures/_Goobstation/Changeling/changeling_abilities.rsi/mindshield.png
  Resources/Textures/_Imp/Mobs/Aliens/pleebnar.rsi/0-equipped-HELMET.png
  Resources/Textures/_Imp/Mobs/Aliens/pleebnar.rsi/meta.json
  Resources/Textures/_Imp/Mobs/Aliens/pleebnar.rsi/pleebnar.png
  Resources/Textures/_Imp/Mobs/Aliens/pleebnar.rsi/pleebnar_harm.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/appendix.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/brain-inhand-left.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/brain-inhand-right.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/brain.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/ears.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/eyeball-l.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/eyeball-r.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/heart-off.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/heart-on.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/kidney-r.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/liver.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/lung-l.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/lung-r.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/meta.json
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/muscle.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/nerve.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/stomach.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/tongue.png
  Resources/Textures/_Imp/Mobs/Species/Gray/organs.rsi/vessel.png
Labels: S: Untriaged, size/L, Changes: Sprites, Changes: UI, Changes: Audio

#89 Thief change
  Content.Server/GameTicking/Rules/ThiefRuleSystem.cs
  Resources/Locale/en-US/_DV/game-ticking/game-rules/preset-thief.ftl
  Resources/Locale/en-US/_DV/prototypes/objectives/thief.ftl
  Resources/Prototypes/GameRules/midround.yml
  Resources/Prototypes/Roles/Antags/thief.yml
Labels: S: Untriaged, size/S

#94 Update workflows
  .github/workflows/labeler-review.yml
  .github/workflows/labeler-untriaged.yml
  .github/workflows/stale.yml
  .github/workflows/update-credits.yml
  Tools/dump_github_contributors.ps1
Labels: Changes: No C#, size/S

#96 add drip to loadout group
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: Changes: No C#

#109 Workflow goida
  .github/workflows/validate-rgas.yml
  Tools/rga_requirements.txt
Labels: size/XS, Changes: No C#

#111 Early port auto target heal
  Content.Shared/Body/Prototypes/BodyPrototypeSerializer.cs
  Content.Shared/Medical/Healing/HealingSystem.cs
Labels: size/M

#113 Add magic crayon
  Content.Client/Crayon/CrayonSystem.cs
  Content.Server/Crayon/CrayonSystem.cs
  Resources/Locale/en-US/_NF/crayon/crayon-component.ftl
  Resources/Locale/en-US/recipes/tags.ftl
  Resources/Prototypes/_NF/Entities/Objects/Fun/magic_crayon.yml
  Resources/Prototypes/_NF/Recipes/Crafting/Graphs/magic_crayon.yml
  Resources/Prototypes/_NF/Recipes/Crafting/magic_crayon.yml
  Resources/Textures/_NF/Objects/Fun/magic_crayon.rsi/icon-inhand-left.png
  Resources/Textures/_NF/Objects/Fun/magic_crayon.rsi/icon-inhand-right.png
  Resources/Textures/_NF/Objects/Fun/magic_crayon.rsi/icon.png
  Resources/Textures/_NF/Objects/Fun/magic_crayon.rsi/meta.json
Labels: size/M, Changes: Sprites

#114 Sparkle Tajaran
  Resources/Prototypes/_Goobstation/Species/tajaran.yml
Labels: size/XS, Changes: No C#

#110 Adding Trooper uniform and hat to Secdrobe
  Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
Labels: size/XS, Changes: No C#
