Repository JamboreeStation/Jamboree-Station, pull requests merged in 2025-08, with the labels that each got.

#6 Port Wiz objectives from DeltaV
  .github/workflows/labeler-pr.yml
  .github/workflows/rsi-diff.yml
  Content.Server/Objectives/Components/FreeObjectiveComponent.cs
  Content.Server/Objectives/Systems/FreeObjectiveSystem.cs
  Resources/Locale/en-US/_DV/objectives/conditions/wizard.ftl
  Resources/Prototypes/Objectives/base_objectives.yml
  Resources/Prototypes/_DV/Objectives/objectiveGroups.yml
  Resources/Prototypes/_DV/Objectives/wizard.yml
  Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml
  Resources/Textures/_DV/Clothing/Head/Hats/propellerhat.rsi/equipped-HELMET.png
  Resources/Textures/_DV/Clothing/Head/Hats/propellerhat.rsi/icon.png
  Resources/Textures/_DV/Clothing/Head/Hats/propellerhat.rsi/meta.json
  Resources/Textures/_DV/Misc/wizard.rsi/meta.json
  Resources/Textures/_DV/Misc/wizard.rsi/scale.png
Labels: S: Untriaged, size/M

#8 Add AGPL License
  LICENSE
Labels: S: Untriaged, size/M, Changes: No C#

#9 Goob merge 8 4 25
  Resources/Changelog/GoobChangelog.yml
  Resources/Prototypes/Entities/Mobs/Species/moth.yml
  Resources/Prototypes/Entities/Structures/Power/chargers.yml
  Resources/Prototypes/GameRules/midround.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/Voice/speech_emote_sounds.yml
  Resources/Prototypes/_DV/CosmicCult/roundstart.yml
  Resources/Prototypes/_EinsteinEngines/Entities/Modsuits/praetorian.yml
  Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
  Resources/Prototypes/_Goobstation/GameRules/midround.yml
  Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
  Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
  Resources/Prototypes/_Goobstation/Wizard/Clothing/wizard.yml
  Resources/Prototypes/_Shitmed/GameRules/events.yml
Labels: S: Untriaged, size/M, Changes: No C#

#10 Climbing cherrypick
  Content.Goobstation.Client/DragDrop/GoobDragDropSystem.cs
  Content.Goobstation.Server/DragDrop/GoobDragDropSystem.cs
  Content.Shared/Climbing/Systems/ClimbSystem.cs
Labels: S: Untriaged, size/S

#16 Readme changes, Im also no designer so enjoy my *PASSION* for graphic…
  README.md
  Resources/Textures/_Jamboree/Logo/bannerLogo.png
Labels: S: Untriaged, Changes: No C#

#18 Init Changelog
  Resources/Changelog/JamboreeChangelog.yml
Labels: S: Untriaged, Changes: No C#, size/S

#19 Update changelog script
  Tools/changelog/changelog.js
Labels: size/XS, Changes: No C#

#21 Add description to the QM bedsheet
  Resources/Locale/en-US/_Jamboree/prototypes/entities/objects/misc/QM_bedsheet.ftl
Labels: size/XS, Changes: No C#, First Contribution!

#28 ideas discussion template
  .github/DISCUSSION_TEMPLATE/IDEA-PROPOSAL.yml
Labels: S: Untriaged, Changes: No C#, size/S

#32 Ideas template
  .github/DISCUSSION_TEMPLATE/ideas.yml
Labels: size/XS, S: Untriaged, Changes: No C#

#35 Add in missing furniture to lpo map
  Resources/Maps/_DV/Nonstations/listening_post.yml
Labels: S: Untriaged, size/M, Changes: No C#, Changes: Map

#36 Changes to Logo, Icons, And Rules
  Resources/Locale/en-US/_Jamboree/changelog/changelog-window.ftl
  Resources/Prototypes/Guidebook/rules.yml
  Resources/Prototypes/_Goobstation/Guidebook/rules.yml
  Resources/ServerInfo/Guidebook/ServerRules/AntagRules/AN01.xml
  Resources/ServerInfo/Guidebook/ServerRules/AntagRules/AN02.xml
  Resources/ServerInfo/Guidebook/ServerRules/AntagRules/AN03.xml
  Resources/ServerInfo/Guidebook/ServerRules/AntagRules/AN04.xml
  Resources/ServerInfo/Guidebook/ServerRules/CommandRules/CO01.xml
  Resources/ServerInfo/Guidebook/ServerRules/CommandRules/CO02.xml
  Resources/ServerInfo/Guidebook/ServerRules/CommandRules/CO03.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/CORE01.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/CORE02.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/CORE03.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/CORE04.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/CORE05.xml
  Resources/ServerInfo/Guidebook/ServerRules/CoreRules/CORE06.xml
  Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RP01.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RP02.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RP03.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RP04.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RP05.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RP06.xml
  Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RP07.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S01.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S02.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S03.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S04.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S05.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S06.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S07.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S08.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S09.xml
  Resources/ServerInfo/Guidebook/ServerRules/SiliconRules/S10.xml
  Resources/Textures/Logo/icon.ico
  Resources/Textures/Logo/icon/icon-128x128.png
  Resources/Textures/Logo/icon/icon-16x16.png
  Resources/Textures/Logo/icon/icon-24x24.png
  Resources/Textures/Logo/icon/icon-256x256.png
  Resources/Textures/Logo/icon/icon-32x32.png
  Resources/Textures/Logo/icon/icon-48x48.png
  Resources/Textures/Logo/icon/icon-64x64.png
  Resources/Textures/Logo/logo.png
  Resources/Textures/Logo/logo_goob.svg
Labels: size/M, Changes: No C#

#37 Add basic discord client integration with ooc and admin chat support …
  Content.Server/Chat/Managers/ChatManager.cs
  Content.Server/Chat/Managers/IChatManager.cs
  Content.Server/Content.Server.csproj
  Content.Server/Discord/DiscordLink/DiscordChatLink.cs
  Content.Server/Discord/DiscordLink/DiscordLink.cs
  Content.Server/Entry/EntryPoint.cs
  Content.Server/IoC/ServerContentIoC.cs
  Content.Server/MoMMI/IMoMMILink.cs
  Content.Server/MoMMI/MoMMILink.cs
  Content.Shared/CCVar/CCVars.Chat.Admin.cs
  Content.Shared/CCVar/CCVars.Chat.Ooc.cs
  Content.Shared/CCVar/CCVars.Discord.cs
  Content.Shared/CCVar/CCVars.Status.cs
  Content.Shared/Chat/ChatChannel.cs
  Directory.Packages.props
  Resources/Locale/en-US/chat/chat-channel.ftl
  Resources/Locale/en-US/chat/managers/chat-manager.ftl
Labels: S: Untriaged, size/M

#38 Switch Discord integration to use NetCord instead of Discord.Net (#38…
  Content.Packaging/ServerPackaging.cs
  Content.Server/Content.Server.csproj
  Content.Server/Discord/DiscordLink/DiscordChatLink.cs
  Content.Server/Discord/DiscordLink/DiscordLink.cs
  Content.Server/Discord/DiscordLink/DiscordSawmillLogger.cs
  Directory.Packages.props
Labels: S: Untriaged, size/M

#39 Discord bot stealing
  Content.Shared/Chat/ChatChannel.cs
Labels: size/XS, S: Untriaged

#40 Fix rules links, also snuck in changelog script change
  Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml
  Tools/actions_changelogs_since_last_run.py
Labels: Changes: No C#

#43 Port DV Custom Objective Text
  Content.Client/UserInterface/Systems/Character/CharacterUIController.cs
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryUIController.cs
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryWindow.xaml
  Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryWindow.xaml.cs
  Content.Server/Objectives/ObjectivesSystem.cs
  Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
  Content.Server/_DV/CustomObjectiveSummary/CustomObjectiveSummarySystem.cs
  Content.Shared.Database/LogType.cs
  Content.Shared/_DV/Abilities/CCVars/DCCVars.cs
  Content.Shared/_DV/CustomObjectiveSummary/CustomObjectiveSummaryComponent.cs
  Content.Shared/_DV/CustomObjectiveSummary/CustomObjectiveSummaryEvents.cs
  Resources/Locale/en-US/_DV/customobjectivesummary/customobjectivesummary.ftl
Labels: S: Untriaged, size/M, Changes: UI

#52 CentComm Event Onboarding
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Jamboree/centcommOnboarding.yml
  Resources/Prototypes/Maps/centcommOnboard.yml
Labels: S: Untriaged, Changes: No C#, Changes: Map, size/XL

#55 1984 some time reqs
  Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Roles/Antags/nukeops.yml
  Resources/Prototypes/Roles/Antags/revolutionary.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chaplain.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/borg.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Roles/requirement_overrides.yml
  Resources/Prototypes/_DV/CosmicCult/cosmiccultist.yml
  Resources/Prototypes/_DV/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/_DV/Roles/Antags/listening_post.yml
  Resources/Prototypes/_Imp/_Drone/Mobs_Player_silicon.yml
  Resources/Prototypes/_Shitmed/Entities/Mobs/Player/abductor.yml
Labels: S: Untriaged, size/M, Changes: No C#

#56 Un-roundstart yowie and resomi. will split guidebook later
  Resources/Prototypes/_Floofstation/Species/resomi.yml
  Resources/Prototypes/_Goobstation/Species/yowie.yml
Labels: S: Untriaged, Changes: No C#, size/S

#72 Yowie/Resomi Guidebook removal
  Resources/Prototypes/Guidebook/species.yml
  Resources/ServerInfo/Guidebook/Mobs/Species.xml
Labels: S: Untriaged, Changes: No C#, size/S
